/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const CardData: typeof import('./shared/components/CardData').default
  const EksekutifData: typeof import('./shared/components/EksekutifData').default
  const Icon: typeof import('./shared/components/Icon').default
  const ListEksekutif: typeof import('./shared/components/ListEksekutif').default
  const LoadData: typeof import('./shared/components/LoadData').default
  const Loader: typeof import('./shared/components/Loader').default
  const PlaceholderSection: typeof import('./shared/components/PlaceholderSection').default
}
// for type re-export
declare global {
  // @ts-ignore
  export type { VLoaderSize, VLoaderWrapperRadius } from './shared/components/Loader'
  import('./shared/components/Loader')
}
