/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const Layout: typeof import('./shared/components/Layout').default
  const LoadData: typeof import('./shared/components/LoadData').default
  const Loader: typeof import('./shared/components/Loader').default
  const PlaceholderSection: typeof import('./shared/components/PlaceholderSection').default
  const Sidebar: typeof import('./shared/components/Sidebar').default
  const Skeleton: typeof import('./shared/components/Skeleton').default
  const ThemeToggle: typeof import('./shared/components/ThemeToggle').default
}
